### ISSUE TITLE
上下的置中彈幕偏右

### ISSUE THREAD

**Issue by Jay920314** [s594569321/MPV-Play-BAHA-Comments#1]
上下的置中彈幕偏右約偏1/5個畫面，撥放的是1080內容 螢幕是2k，視窗大小不影響偏右
沒大病但看著不舒服，檔案除了字體都看無 字體後面幾個數字調了感覺也沒啥關聯

除此之外功能很棒謝謝作者

**Comment by s594569321** [comment]
> 上下的置中彈幕偏右約偏1/5個畫面，撥放的是1080內容 螢幕是2k，視窗大小不影響偏右 沒大病但看著不舒服，檔案除了字體都看無 字體後面幾個數字調了感覺也沒啥關聯
> 
> 除此之外功能很棒謝謝作者

不好意思現在才看到，彈幕偏右的問題已修正，再麻煩重抓新版的就可以了
