### ISSUE TITLE
頂部彈幕超出影片

### ISSUE THREAD

**Issue by 45380172** [s594569321/MPV-Play-BAHA-Comments#2]
頂部(TOP)的彈墓的MarginV值似乎設得太大導致頂部彈墓時常看不到，螢幕2K ,動畫用anime4k拉伸至2K，我自己測試用480左右會好一些，因為遇到同時有多彈墓在頂部時字往上擠， 另外建議可以直接用python來運行腳本，修改數值較方便

**Comment by s594569321** [comment]
> 頂部(TOP)的彈墓的MarginV值似乎設得太大導致頂部彈墓時常看不到，螢幕2K ,動畫用anime4k拉伸至2K，我自己測試用480左右會好一些，因為遇到同時有多彈墓在頂部時字往上擠， 另外建議可以直接用python來運行腳本，修改數值較方便

不用 Python 運行只是考慮到有部分受群可能沒有裝 Python，如果會改的話，Python 和 Lua 本體都有可以自行更改
